server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: client-route
          uri: lb://client
#          uri: http://localhost:8081
          predicates:
            - Path=/client/**
        - id: mobile-route
          uri: lb://mobile
#          uri: http://localhost:8082
          predicates:
            - Path=/mobile/**
#          filters:
#            - AddRequestHeader=Truth,talk is cheap
      default-filters:
        - AddRequestHeader=Truth,talk is cheap show me the code

    nacos:
      server-addr: localhost:8848
      discovery:
        locator:
          enabled: true