server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /
    port: 5672
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss
