server:
  port: 8081
spring:
  application:
    name: client
  cloud:
    nacos:
      server-addr: localhost:8848
feign:
  client:
    config:
      default:
        ConnectTimeout: 10000
        readTimeout: 60000
  circuitbreaker:
    enabled: true
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50